In [1]:
#Country - Age - Salary - Purchased 
#Independent variables (Country - age - salary), we will predict the 
#Dependent variable (purchased)

In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 

In [21]:
dataset = pd.read_csv('C:\Developer\Data Science\Machine Learning Udemy Course\Machine-Learning-A-Z-New\Machine Learning A-Z New\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [22]:
# Matrix of features (Matrix of independent variables)
X = dataset.iloc[:, :-1].values  #Take everything before the comma. #take everthing after the comma except last one.
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [54]:
#The Last Column (Dependent Variable)
y = dataset.iloc[:, :3].values
y 

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [55]:
# Taking care of Missing values 
# You should not remove rows, but instead take the mean of the values in the column 

from sklearn.preprocessing import Imputer 
imputer = Imputer(missing_values='NaN', strategy = 'mean', axis = 0) #strategy can be median
imputer.fit(X[:, 1: 3]) 
X[:, 1:3] = imputer.transform(X[:, 1:3])  #selecting commons were there's missing data
X    #Germany's missing salasry was fillef with the mean. This is not changing the dataset yet. 

C:\Users\matth\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[    1,     0,     1,     0,     1,     0,     0,    44, 72000],
       [    0,     1,     0,     1,     0,     0,     1,    27, 48000],
       [    0,     1,     0,     1,     0,     1,     0,    30, 54000],
       [    0,     1,     0,     1,     0,     0,     1,    38, 61000],
       [    0,     1,     0,     1,     0,     1,     0,    40, 63777],
       [    1,     0,     1,     0,     1,     0,     0,    35, 58000],
       [    0,     1,     0,     1,     0,     0,     1,    38, 52000],
       [    1,     0,     1,     0,     1,     0,     0,    48, 79000],
       [    0,     1,     0,     1,     0,     1,     0,    50, 83000],
       [    1,     0,     1,     0,     1,     0,     0,    37, 67000]])

In [66]:
#encoding categorical data (Country and Purchased). Text data has to be encoded to numbers. 

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_X = LabelEncoder()
X[:, 0] = labelEncoder_X.fit_transform(X[:, 0])# : = all the lines - of column 0
X  #The first column is encoded

# The problem is that the model would think that spain has a higher value than germany or vice versa
# There's no order between the countries and they're the same - they're categories!
# To prevent this, we will use dummy variables, and make 3 columns, one for each country.
# We need another class : OneHotEncoder

onehotencoder = OneHotEncoder(categorical_features= [0])
X = onehotencoder.fit_transform(X).toarray()  ##Country is replaced by 3 columns. 1 = on. 0 = off
X = X.astype(int)
X   #Not good since multipe Columns 


C:\Users\matth\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\matth\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[    0,     1,     0,     0,    44, 72000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,    30, 54000],
       [    1,     0,     0,     1,    38, 61000],
       [    1,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    35, 58000],
       [    1,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    1,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

In [59]:
# For purchased column, since it's the dependent variable, the machine learning
# model will know its a category. Therefore labelEncoder will be used.
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)



ValueError: bad input shape (10, 3)

In [67]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('C:\Developer\Data Science\Machine Learning Udemy Course\Machine-Learning-A-Z-New\Machine Learning A-Z New\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y
X.astype(int)    #correct

C:\Users\matth\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\matth\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\matth\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_fea

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [85]:
# Splitting the Dataset into: test set and training set 
# You have to test the model on new data. 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size = 0.2, random_state = 0) #X = matrix of features y= dependent variable



In [90]:
# Feature Scaling
# Since age and salary variables have different scales, they will cuase issue in the ml model
# this is becuase the ml model uses the euclidiean distance. Since the salary is much larger
# the euclidean distance will be domnated by the salary. 
# 31000 salary squared gives a large number
# 21 age squared gives just 221. Therefore this will not make any difference

# Therefore, both age and salary should be made to range from example -1 to 1. 
# Feature Scaling: Standardisation or Normalisation 

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) # the sc object is already fitted to the training set

# Do you need to scale the dummy variables? 
# Answer: It depends. How much you want to keep interpretation in your models.

# Some ML models do not use the eculidean distance (such as decision trees)
# but it's still better to scale them up, because they will run faster 



array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [93]:
# Data Processing Template 

# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, -1].values
y = dataset.iloc[:, 3].values

# Splitting the dataset intoTraining set and Test set 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size = 0.2, random_state = 0) #X = matrix of features y= dependent variable

# Feature Scaling 

FileNotFoundError: [Errno 2] File b'Data.csv' does not exist: b'Data.csv'